excluded:
  - Pods
  - DerivedData
opt_in_rules:
  - force_unwrapping
large_tuple: 3
line_length:
  warning: 200
  error: 350
function_body_length:
  warning: 40
  error: 80
type_body_length:
  warning: 200
  error: 400

